import React, { useState } from 'react';
import { AgentProject } from '../types';
import { 
  X, 
  Copy, 
  Check, 
  Download
} from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  project: AgentProject;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, project }) => {
  const [activeTab, setActiveTab] = useState<'python' | 'json' | 'yaml' | 'langgraph'>('python');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const getExportCode = () => {
    if (activeTab === 'python') {
      return `# Generated by twinerun (Profile-Guided Optimizer)
# Target: ${project.name} · Version: ${project.version} · Optimization: -${project.savingsPct}%
import agent_pgo

# Compiled Execution Configuration
pgo_manifest = agent_pgo.load_manifest({
    "agent_id": "${project.id}",
    "version": "${project.version}",
    "baseline_cost": ${project.baselineCost},
    "optimized_cost": ${project.optimizedCost},
    "nodes": {
${project.nodes.map((n) => `        "${n.id}": {"model": "${n.optimizedModel}", "sensitivity": "${n.qualitySensitivity}"}`).join(',\n')}
    }
})

@agent_pgo.compiled(manifest=pgo_manifest)
def run_research_pipeline(query: str):
    # Agent execution automatically routes to compiled models
    ...
`;
    }

    if (activeTab === 'json') {
      return JSON.stringify(
        {
          schema_version: 'pgo.v1',
          agent_name: project.name,
          environment: project.environment,
          version: project.version,
          metrics: {
            baseline_cost_per_req: project.baselineCost,
            compiled_cost_per_req: project.optimizedCost,
            savings_pct: project.savingsPct,
            baseline_latency_p95: project.baselineLatencyP95,
            compiled_latency_p95: project.optimizedLatencyP95,
            eval_quality_score: project.optimizedQuality
          },
          nodes: project.nodes.map((n) => ({
            id: n.id,
            name: n.name,
            baseline_model: n.baselineModel,
            compiled_model: n.optimizedModel,
            cost_share_pct: n.costSharePct,
            quality_sensitivity: n.qualitySensitivity
          }))
        },
        null,
        2
      );
    }

    if (activeTab === 'yaml') {
      return `version: "twinerun/v1"
agent: "${project.name}"
env: "${project.environment}"
savings: "${project.savingsPct}%"
nodes:
${project.nodes.map((n) => `  - id: "${n.id}"\n    name: "${n.name}"\n    model: "${n.optimizedModel}"\n    sensitivity: "${n.qualitySensitivity}"`).join('\n')}
verification:
  eval_cases: ${project.evalCasesCount}
  tolerance_pct: ${project.qualityTolerancePct}
  confidence: "${project.confidencePct}%"
  status: "PASS"
`;
    }

    return `# LangGraph PGO Gateway Integration
from langgraph.graph import StateGraph
from agent_pgo.langgraph import wrap_pgo_nodes

workflow = StateGraph(ResearchState)
# Wire nodes...
workflow.add_node("planner", planner_step)
workflow.add_node("researcher", researcher_step)
workflow.add_node("extractor", extractor_step)
workflow.add_node("reasoner", reasoner_step)
workflow.add_node("formatter", formatter_step)

# Apply twinerun compiled routing
compiled_app = wrap_pgo_nodes(workflow, pgo_spec_id="${project.id}-${project.version}")
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getExportCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-[#050505]/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div 
        className="fixed inset-0" 
        onClick={onClose} 
      />
      <div className="w-full max-w-2xl bg-[#090A0B] border border-white/[0.08] rounded-lg shadow-2xl overflow-hidden z-10 font-mono text-xs flex flex-col">
        {/* Header */}
        <div className="p-3.5 border-b border-white/[0.05] flex items-center justify-between bg-[#0F1113]">
          <div className="flex items-center gap-2">
            <Download className="w-4 h-4 text-[#D7DADD]" />
            <span className="font-semibold text-xs text-[#F2F3F4] tracking-wide uppercase">
              EXPORT COMPILED PGO MANIFEST
            </span>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded text-[#5C6268] hover:text-[#D7DADD] transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Format Switcher */}
        <div className="flex items-center border-b border-white/[0.05] bg-[#090A0B] px-3">
          {(['python', 'json', 'yaml', 'langgraph'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`py-2 px-3 border-b-2 transition-colors text-xs uppercase font-medium ${
                activeTab === tab
                  ? 'border-[#D7DADD] text-[#F2F3F4]'
                  : 'border-transparent text-[#5C6268] hover:text-[#D7DADD]'
              }`}
            >
              {tab === 'python' ? 'Python SDK' : tab === 'json' ? 'JSON Manifest' : tab === 'yaml' ? 'YAML Spec' : 'LangGraph'}
            </button>
          ))}
        </div>

        {/* Code Content */}
        <div className="p-4 bg-[#050505] flex-1 overflow-y-auto max-h-96">
          <pre className="text-[11px] text-[#D7DADD] font-mono leading-relaxed selection:bg-white/[0.1]">
            {getExportCode()}
          </pre>
        </div>

        {/* Footer */}
        <div className="p-3 border-t border-white/[0.05] bg-[#050505] flex items-center justify-between">
          <span className="text-[#5C6268] text-[10px]">
            Target: {project.name} · -{project.savingsPct}% Execution Cost
          </span>
          <button
            onClick={handleCopy}
            className="px-3.5 py-1.5 rounded silver-btn-gradient text-[#050505] font-bold flex items-center gap-1.5 shadow-sm transition-all"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Manifest</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

